### PR TITLE
M1 python eda 1 (Changing dtype of the data and Load just columns we want)

### LINKED ISSUE #8: Load combined csv to memory and perform simple EDA & Discussions (Saule)
- [ ] Changing dtype of your data (Saule)
- [ ] Load just columns what we want (Saule)

### PR DESCRIPTION
**Pull request by Saule-Atymtayeva**
Mai, please, review this PR.
Here I'm:
- Changing dtype of the columns.
- Dropping some columns.
- Making the observations.

Thank you!

### CODE REVIEW

**Comment by lephanthuymai** [comment]
Hi @Saule-Atymtayeva, 
My first impression is that you have given this task a lot of thought, thank you!
I have a couple of questions and suggestions as below:
1. Changing data type:
* Should we write a function to check the data type and use it for all columns? I'm thinking of something like is_compatible( object, datatype) which will return True if we can convert the object (a column) to a certain datatype. 
* We can then add all results of all columns into a data frame, we can also calculate the memory saving by the conversion. After that we just print the data frame out, it will give a clearer summary, I think.
* Later in the high level summary (Our observations), we can briefly mention about the list of possible conversion and total memory saving
2. Load just columns we want: I'm curious as why we don't need lat_min and lon_min :P

Hope this helps.
Thank you very much.
Best,
Mai

**Comment by Saule-Atymtayeva** [comment]
Hey @lephanthuymai!

Thank you for your detailed review! I appreciate it!

1. I have updated the code by creating a function that checks the float64 columns that can be changed into the float32 type (the function is specific for this exercise). Though your suggestions are great, in my opinion we don't have to go so far 😅 And, by looking at the data it's easy to determine an appropriate type for certain columns. Let's stick on that for now 😔
2. As I am mentioning in the summary, we just suppose that we don't need some data. In my understanding, the main purpose of the task is to show that reducing the number of columns can reduce memory usage. For this reason, I chose some minimum values to drop them 🙂

Thank you again!

**Comment by Saule-Atymtayeva** [comment]
@lephanthuymai Hey Mai!

Thank you so much for your thorough review! I appreciate it.

With your help I did the following:

1. I created two summary tables, one of them is for checking whether the numeric columns are within the range of float32 data type, and the second one is for showing the memory savings for each column. I hope, you will like the results, and it is easier to understand our intentions 🙂
2. As I am mentioning in the conclusion, we just suppose that some of the columns are not so important. In reality, it depends on the prediction problem. And we haven't started creating our ML model yet. So, let's suppose that we don't need these two columns 😅 In my understanding, we need to show the reduction in the memory usage when dropping some columns.

I've updated the code.

Thank you again!

**Comment by lephanthuymai** [comment]
Dear @Saule-Atymtayeva ,
Thank you very much for putting up with me, sometimes my perfectionist just got a hold of me!
The latest changes look awesome!
Best,
Mai

**Review by lephanthuymai — APPROVED** [review]
Great job! Thanks!

**Pull request merged**
