### PR TITLE
Update submission notebook

### LINKED ISSUE #30: 3. Develop a ML model using scikit-learn.
ubric={correctness:25}

Upload this notebook to your jupyterHub (TLJH in your EC2) from your previous milestone and follow instruction given there. https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3-Task3.ipynb

### LINKED ISSUE #31: 4. Obtain best hyperparameter settings using spark's MLlib.
rubric={correctness:20}

Upload this notebook to your jupyterHub (AWS managed jupyterHub in cluster) you setup in Task 2 and follow instruction given there. https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3-Task4.ipynb

### PR DESCRIPTION
**Pull request by lephanthuymai**
Hi Team,
Please help to review and merge my PR with changes described below:
* M3_notebook.ipynb: our submission notebook, will put its link to Canvas
* Milestone3-Task3.ipynb: re-run with the new results from task 4
* Milestone3-Task4.ipynb: latest file provided by Saule
Thank you.
Best,
Mai

### CODE REVIEW

**Review by tdkhanhvu — APPROVED** [review]
Both notebooks look good to me

**Review by Saule-Atymtayeva — APPROVED** [review]
Everything looks fine to me! Thank you, Mai!

**Comment by rainbowxyt0305** [comment]
Thank you @lephanthuymai for putting everything together! Here are my reviews on `Milestone3-Task3.ipynb`:

- [see screenshot 1] could you please complete the title for `step 5` and `step 6` (somethign like `Step 5: Train ensemble ML model` and `Step 6: Results discussion` - the same brief description as in previous steps)?
- [see screenshot 2] there is a typo `indivitual`
- [see screenshot 3] could you please suppress the message by adding `;`?
- [see screenshot 4] could you please remove any unnecessary cells as you see fit (i.e. marked red below) and change highlighted text to `Uploaded model.joblib to s3.` ?

image
image
image
image

**Comment by lephanthuymai** [comment]
Hi Team,
Thank you very much for your review!

@rainbowxyt0305 : I have fixed the notebook as listed in your comments, please have a look. Thank you very much!

Mai

**Pull request merged**
